name: Scrape Airbnb Dubai
on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.40.0
          playwright install --with-deps chromium

      - name: Run scraper
        env:
          LOCATION: "Dubai, United Arab Emirates"
          MAX_LISTINGS: "250"   # commence à 250 pour tester
          SCROLLS: "30"
        run: |
          python scrape_airbnb.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: airbnb-dubai-csv
          path: airbnb_dubai_listings.csv
